### ISSUE TITLE
Configuration users

### ISSUE THREAD

**Issue by faridy95** [CyCoreSystems/asterisk-config#6]
hello, I would like to congratulate you on this project.
I have installed and configured but I have a problem with the test I would like to know how a user A can reach another user B with asterisk-config.

**Comment by Ulexus** [comment]
This tool is not opinionated in your method of defining "users" to your system.  You can use database backends, file-oriented endpoints, flat-files, etc.  Anything which Asterisk can support should be enscribeable by this tool.

If you have a particular integration which you think would be useful to explore more fully, please feel free to suggest it.
